name: "Bug Report"
description: File a bug report for the CountUp menu bar app.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug in CountUp.
        Please fill in the information below so we can understand the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue and what you expected to happen instead.
      placeholder: Tell us what you saw…
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: App Version
      description: Which version of CountUp are you using?
      options:
        - 1.0
        - 2.0
      default: 0
    validations:
      required: true

  - type: dropdown
    id: macos
    attributes:
      label: macOS Version
      description: Which macOS version are you running?
      options:
        - macOS 13 (Ventura)
        - macOS 14 (Sonoma)
        - macOS 15 (Sequoia)
      default: 0
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Open CountUp
        2. Press Start
        3. ...
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional Information
      description: Anything else we should know?
    validations:
      required: false
